dist: trusty
sudo: required

addons:
  sonarqube:
    token:
      secure: "Awsl5TV1OG8M+JinBj/kOfQHepsWnHnNsUE/MkOh9Q4UL6Hqu/oYV37AgWTc3WxV2mjF9J0kvgVN9X8Gx343enb0HfXw4v8b7UvRtFPTmGNryenpKS2Fwj/04yMgbJmuxip+bV+7TP0Nh7ri8p1frrCflMAQae6itdBB0w2FYqAsvRSixVCD41wdsr7gFTzRRgST9F4j4tas+nHWwkNESJWI7JbaWa9sGqhb9mvRmuvXpAwMzFCxiljWf/61Ye1KvvkmESJ/glTOJ5q82e9FD9oU0wqjUhVJa+bxCCuhu08zRilJh3Vajmamhc2SlegR6CvbnLqkX4aKbWLfIKqoXJ93WoTHKSZXxyscDeXkbW8easvuzuWmF3FFGvsdyp/gmY5sza4AypU/v1l54fArDMbafDal9zcieB5+VffXgXCAixs8K0zayU8o0zmLPijbmTnEuDwCCA0NySkNYbnZu5nfwsexNWVBuvk2d0bKSgGycZMJHJsW2dc2Zd13aNguQXqf8Un2va8I+ERn96uaIF5XjhIuJRZpjo81ZNV6q/PxTIEY6RFuxY1U4QEtA6kUfpQW3zxesCI3VKtT/L0+akc3JT797xTu+6WROneE3b/WCEZT3RdhE/AGj4OcMn4Y2STEbDY+vQ4FkfKdriyzAn0H2jPnal2psrur12oQJO0="
    github_token:
        secure: "bmNMywZmaEX0J3n3w62t4knBlEy2VcLQQ3gg4q2JvH9DhIwg9aJZCsPAZI+VJp/SWvECzj7OAnTfo2LKgdONQEspPjp+6X+eJHVnijIKRFb33w6BUcju3oOUiGSUv7ODHsu1tzk27dIsxAJoLad29mmSnpchb9AxSGlsuL+Z54//q22cHimEu242eQZ9XbF7JQJNahYKYVurDj1TaTvyp1uMimcHdzuHoMopZzFno71NTamhXWh+XxJq6ScbVa2Z4+0+LtQWMU3aIzESR6ni8QQ+F3dMjv5OarRHDHlS3qmGyuJfd6TcPD3E5dpOcp/bjAbqUYNrqijUa/uow1gWiIi8RdLBG3/N+igTgJdv2alPwf2kyqJkg/uGxC4rJmTUoNMrmZ31ZtOFCCfWcbc5m0Wcx/bwJQNkyU/ExOJHPQJfYeSBYOd3BmherbW8b89hoD/AQZJzvGZ1cCffbuHVGag/ATcNTBgSjcdyJuJdSulmLRkctVrnqkDR7hLZ+wsUzqEwbTrzc/beIhHcqWsH5iVRSuc3FwKeN+owsWvlW+X5lyWnhYqy4iJ/IwFTVxkGyHAQXpa8rV6QNv0W8aKHu0hhzRxUZ1aPG1dz9ZtrC1NqZDmbHnc+XlqJC0/jcGED0Ongmbl1LY08qQinvNWWBeXntFS2ZmRXScFUlQW19TI="
  branches:
      - master
jdk:
  - oraclejdk8
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.sonar/cache'
